CREATE TABLE IF NOT EXISTS plivacki_kalendar (
  kalendar_id INT AUTO_INCREMENT PRIMARY KEY,
  godina INT NOT NULL DEFAULT 2026,
  naziv_takmicenja VARCHAR(255) NOT NULL,
  klub_savez_id INT NULL,
  klub_savez_naziv VARCHAR(255) NULL,
  lokacija_grad VARCHAR(100) NOT NULL DEFAULT 'Banja Luka',
  bazen_naziv VARCHAR(150) NULL,
  tip_lokacije ENUM('DOMACI', 'TEREN_BLIZU', 'TEREN_DALEKO') NOT NULL DEFAULT 'DOMACI',
  datum_od DATE NOT NULL,
  datum_do DATE NOT NULL,
  datum_polaska DATE NULL,
  datum_povratka DATE NULL,
  broj_takmicarskih_dana INT NOT NULL DEFAULT 2,
  ukupno_blokiranih_dana INT NOT NULL DEFAULT 2,
  nocenja_broj INT NOT NULL DEFAULT 0,
  nocenje_pokriva ENUM('ORGANIZATOR', 'STUDIO_TAF', 'BEZ_NOCENJA') NOT NULL DEFAULT 'BEZ_NOCENJA',
  nocenje_cijena_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  kilometraza_km INT NOT NULL DEFAULT 0,
  trosak_goriva_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  putarine_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  dnevnice_mjerioca_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  ugovoreni_pausal_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  neto_zarada_km DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
  status ENUM('PLANIRANO', 'POTVRDJENO', 'U_TOKU', 'ODRZANO', 'OBRADJENO', 'FAKTURISANO', 'NAPLACENO') NOT NULL DEFAULT 'PLANIRANO',
  napomena TEXT NULL,
  projekat_id INT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_godina (godina),
  INDEX idx_datum (datum_od)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
