-- Migracija za tabelu osnovna_sredstva
CREATE TABLE IF NOT EXISTS osnovna_sredstva (
  id INT AUTO_INCREMENT PRIMARY KEY,
  naziv VARCHAR(255) NOT NULL,
  kategorija ENUM('IT_RACUNARI', 'AUDIO_STUDIO', 'TERENSKA_MJERENJE', 'VOZILO', 'OSTALO') NOT NULL DEFAULT 'IT_RACUNARI',
  serijski_broj VARCHAR(100) NULL,
  datum_nabavke DATE NOT NULL,
  nabavna_vrijednost_km DECIMAL(12,2) NOT NULL DEFAULT 0.00,
  stopa_amortizacije DECIMAL(5,2) NOT NULL DEFAULT 20.00,
  porijeklo ENUM('LICNA_IMOVINA_UNOS', 'FAKTURA_DOBAVLJAC', 'UGOVOR_FIZICKO_LICE') NOT NULL DEFAULT 'LICNA_IMOVINA_UNOS',
  opis_namjene TEXT NULL,
  status ENUM('U_UPOTREBI', 'RASHODOVANO', 'PRODATO') NOT NULL DEFAULT 'U_UPOTREBI',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
